# core/dna.py

import os
from collections import Counter

# Direct binary to DNA mapping (used for message encoding only)
BIN_TO_DNA = {'00': 'A', '01': 'T', '10': 'C', '11': 'G'}
DNA_TO_BIN = {v: k for k, v in BIN_TO_DNA.items()}

# Purines (A, G) vs Pyrimidines (C, T) -- used for 5PPD
PURINES = {'A', 'G'}

def text_to_bits(text: str) -> str:
    """Convert a text string into a binary bit string."""
    return ''.join(f'{byte:08b}' for byte in text.encode('utf-8'))

def bits_to_text(bits: str) -> str:
    """Convert a binary bit string back into a text string."""
    if len(bits) % 8 != 0:
        raise ValueError(f"Bit string length {len(bits)} is not a multiple of 8. Decryption may have used the wrong key.")
    chars = [bits[i:i+8] for i in range(0, len(bits), 8)]
    return bytes(int(c, 2) for c in chars).decode('utf-8')

def encode_dna(bits: str) -> str:
    """
    Encode a bit string into a DNA sequence (2 bits per base).
    Raises if the bit string length is not a multiple of 2 -- no silent padding.
    """
    if len(bits) % 2 != 0:
        raise ValueError(f"Bit string length {len(bits)} is not a multiple of 2.")
    return ''.join(BIN_TO_DNA[bits[i:i+2]] for i in range(0, len(bits), 2))

def decode_dna(sequence: str) -> str:
    """
    Decode a DNA sequence back into a bit string.
    Raises ValueError on invalid bases instead of a raw KeyError.
    """
    valid = set(DNA_TO_BIN.keys())
    for base in sequence:
        if base not in valid:
            raise ValueError(f"Invalid DNA base '{base}'. Expected one of {sorted(valid)}.")
    return ''.join(DNA_TO_BIN[base] for base in sequence)

def generate_key(length_bases: int) -> str:
    """
    Generate a cryptographically secure random DNA key using os.urandom().

    os.urandom() draws entropy from the OS (hardware sources: CPU timing,
    hardware interrupts, etc.) unlike random.choice() which is a deterministic
    PRNG seeded from the clock. This is the recommended source for cryptographic
    applications in Python (see: PEP 506, secrets module).

    Each pair of random bits maps to one DNA base:
        00 -> A, 01 -> T, 10 -> C, 11 -> G
    """
    bases = []
    # ceil(length_bases / 4) bytes -- each byte yields exactly 4 bases (4 x 2 bits)
    # e.g. length_bases=5 -> n_bytes=2 -> 8 bases generated, 5 kept
    # The 3 discarded bases are unused entropy -- not a bug, just byte-boundary rounding
    n_bytes = (length_bases + 3) // 4
    raw = os.urandom(n_bytes)
    for byte in raw:
        for shift in (6, 4, 2, 0):
            two_bits = (byte >> shift) & 0b11
            bases.append(['A', 'T', 'C', 'G'][two_bits])
    return ''.join(bases[:length_bases])

def purine_parity_digitize(sequence: str, block_size: int = 5) -> str:
    """
    Block-5 Purine Parity Digitization (5PPD) as described in the CNRS paper.

    For each block of `block_size` bases, count the number of purines (A or G)
    modulo 2. This produces one bit per block.

    Why 5PPD instead of direct encoding?
    Direct encoding (00=A, 01=T...) is sensitive to synthesis biases: if A
    appears more often than G during chemical synthesis, the resulting bits
    are not uniformly distributed. 5PPD averages over positional biases and
    short-range correlations along the polymer chain, producing bits that
    pass NIST SP 800-90B entropy requirements (as demonstrated in the paper).

    Note: in this software simulation, the key is generated by os.urandom()
    and has no synthesis bias. 5PPD is implemented here for pedagogical
    demonstration of the CNRS method only.
    """
    bits = []
    for i in range(0, len(sequence) - block_size + 1, block_size):
        block = sequence[i:i + block_size]
        purine_count = sum(1 for base in block if base in PURINES)
        bits.append(str(purine_count % 2))
    return ''.join(bits)

def xor_bits(bits1: str, bits2: str) -> str:
    """XOR two bit strings of equal length."""
    return ''.join(str(int(a) ^ int(b)) for a, b in zip(bits1, bits2))

def xor_sequences(seq1: str, seq2: str) -> str:
    """Perform a bitwise XOR on two DNA sequences via their binary representations."""
    bits1 = decode_dna(seq1)
    bits2 = decode_dna(seq2)
    xored = xor_bits(bits1, bits2)
    return encode_dna(xored)

def encrypt(message: str, key: str) -> str:
    """Encrypt a message using a DNA key (OTP)."""
    bits = text_to_bits(message)
    # text_to_bits always returns a multiple of 8 bits -- safe to encode directly
    dna_message = encode_dna(bits)
    if len(key) < len(dna_message):
        raise ValueError("Key must be at least as long as the message.")
    return xor_sequences(dna_message, key[:len(dna_message)])

def decrypt(ciphertext: str, key: str) -> str:
    """
    Decrypt a message using the same DNA key.
    Raises explicitly if the bit length is not a multiple of 8.
    """
    if len(key) < len(ciphertext):
        raise ValueError("Key must be at least as long as the ciphertext.")
    decrypted_dna = xor_sequences(ciphertext, key[:len(ciphertext)])
    bits = decode_dna(decrypted_dna)
    return bits_to_text(bits)